# Generated by Django 4.2.1 on 2023-05-26 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('title', models.CharField(max_length=50)),
                ('salary', models.FloatField()),
                ('image', models.ImageField(upload_to='img')),
                ('description', models.CharField(max_length=400)),
                ('experience', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=400)),
                ('skills', models.CharField(max_length=200)),
                ('creation_date', models.DateField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.company')),
            ],
        ),
    ]
