# Generated by Django 4.2.1 on 2023-05-26 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('resume', models.ImageField(upload_to='img')),
                ('apply_date', models.DateField()),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.applicant')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.job')),
            ],
        ),
    ]
